baseurl = "https://tanstaafl.0pt.jp/"
languageCode = "ja-jp"
title = "フリーランチなど無い - There ain't no such thing as a free lunch"
author = "Minori Tokuda (@snowcrush)"
hasCJKLanguage = true
buildFuture = true
theme = "hacked"
publishdir = ".."

[taxonomies]
tags = "tags"