baseurl = "https://tanstaafl.0pt.jp/"
languageCode = "ja-jp"
title = "フリーランチなど無い - There ain't no such thing as a free lunch"
author = "Minori Tokuda (@snowcrush)"
hasCJKLanguage = true
buildFuture = true
theme = "julius"
publishdir = ".."
googleAnalytics = "G-WMCEBYW7WE"

[Params]
images = ["images/simple_thumbnail.png"]

[taxonomies]
tags = "tags"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
linenos = true
tabWidth = 2
lineNumbersInTable = false
