baseurl = "https://tanstaafl.0pt.jp/"
languageCode = "ja-jp"
title = "フリーランチなど無い - There ain't no such thing as a free lunch"
author = "Minori Tokuda (@snowcrush)"
hasCJKLanguage = true
buildFuture = true
theme = "hacked"
publishdir = ".."
googleAnalytics = "UA-19366665-1"

[Params]
images = ["images/sakura_thumbnail.jpg"]

[taxonomies]
tags = "tags"
